version: 2.1
orbs:
  node: circleci/node@5.2.0
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  User API:
    docker:
      - image: cimg/node:20.4.0-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install-packages
      - run:
          name: Run TestCafe tests on headless Chrome
          command: npm test

workflows:
  end-to-end-tests:
    jobs:
      - User API
