version: 2.1
orbs:
  node: circleci/node@4.3.0
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  test:
    docker:
      - image: circleci/node:20.4.0-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test
